---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  import_playbook: playbook-setup-only.yml

  tasks:
   - name: Schedule a conditional reboot
     command:
       cmd: /usr/local/sbin/coreboot --force
       creates: /run/coreboot-scheduled
